//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200: Codable {

    /** number of result passed my \&quot;limit\&quot; value */
    public var resultCount: Int?
    public var results: [Result]?

    public init(resultCount: Int?, results: [Result]?) {
        self.resultCount = resultCount
        self.results = results
    }


}

