//
// SearchAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SearchAPI {
    /**
     * enum for parameter media
     */
    public enum Media_searchByTerm: String { 
        case movie = "movie"
        case podcast = "podcast"
        case music = "music"
        case musicvideo = "musicVideo"
        case audiobook = "audiobook"
        case shortfilm = "shortFilm"
        case tvshow = "tvShow"
        case software = "software"
        case ebook = "ebook"
        case all = "all"
    }

    /**
     Search itunes with term
     
     - parameter term: (query) The URL-encoded text string you want to search for.  For example: jack+johnson.  URL encoding replaces spaces with the plus (+) character and all characters except the following are encoded: letters, numbers, periods (.), dashes (-), underscores (_), and asterisks (*)  
     - parameter country: (query) The two-letter country code for the store you want to search. The search uses the default store front for the specified country.  See [ISO 3166](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)  
     - parameter media: (query) The media type you want to search for.   (optional, default to all)
     - parameter limit: (query) The number of search results you want the iTunes Store to return.  value allowed for [1, 200]  (optional, default to 50)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func searchByTerm(term: String, country: String, media: Media_searchByTerm? = nil, limit: Int? = nil, completion: @escaping ((_ data: SearchResponse?,_ error: Error?) -> Void)) {
        searchByTermWithRequestBuilder(term: term, country: country, media: media, limit: limit).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Search itunes with term
     - GET /search
     - - It is critical to encode your URLs correctly in order to be commissioned for partner links. Notes on partners encoding raw links can be found in the Advanced Partner Linking document.  - To improve response times, minimize the number of search results the Search API returns by specifying an appropriate value for the limit parameter key.  - The Search API is limited to approximately 20 calls per minute (subject to change). If you require heavier usage, we suggest you consider using our Enterprise Partner Feed (EPF).  If you wish to access content on our EPF, please review our documentation page for more information.  - Large websites should set up caching logic for the search and lookup requests sent to the Search API. For an illustration, see Caching Architecture later in this document. 
     - examples: [{contentType=application/json, example={
  "resultCount" : 50,
  "results" : [ {
    "artworkUrl100" : "http:// a1.itunes.apple.com/jp/r10/Music/ y2005/m06/d03/h05/s05.oazjtxkw.100×100-75.jpg",
    "trackTimeMillis" : 210743,
    "country" : "USA",
    "previewUrl" : "http:// a392.itunes.apple.com/jp/r10/ Music/y2005/m06/d03/h05/s05.zdzqlufu.p.m4p",
    "artistId" : 909253,
    "trackName" : "Banana Pancakes",
    "collectionName" : "In Between Dreams",
    "artistViewUrl" : "http:// itunes.apple.com/WebObjects/ MZStore.woa/wa/viewAlbum?i=68615807&id=68615813&s=143462",
    "discNumber" : 1,
    "trackCount" : 14,
    "wrapperType" : "track",
    "currency" : "USD",
    "collectionId" : 120954021,
    "isStreamable" : true,
    "trackExplicitness" : "track",
    "collectionViewURL" : "http:// itunes.apple.com/WebObjects/ MZStore.woa/wa/viewAlbum?i=68615807&id=68615813&s=143462",
    "trackNumber" : 1,
    "trackId" : 120954025,
    "kind" : "book",
    "collectionPrice" : 10.99,
    "discCount" : 1,
    "primaryGenreName" : "Rock",
    "trackPrice" : 0.99,
    "collectionExplicitness" : "track",
    "artworkUrl60" : "http:// a1.itunes.apple.com/jp/r10/Music/ y2005/m06/d03/h05/s05.oazjtxkw.60×60-75.jpg",
    "trackViewUrl" : "http:// itunes.apple.com/WebObjects/ MZStore.woa/wa/viewAlbum?i=68615807&id=68615813&s=143462",
    "trackCensoredName" : "S**t Happens",
    "artistName" : "Jack Johnson",
    "collectionCensoredName" : "S**t Happens"
  }, {
    "artworkUrl100" : "http:// a1.itunes.apple.com/jp/r10/Music/ y2005/m06/d03/h05/s05.oazjtxkw.100×100-75.jpg",
    "trackTimeMillis" : 210743,
    "country" : "USA",
    "previewUrl" : "http:// a392.itunes.apple.com/jp/r10/ Music/y2005/m06/d03/h05/s05.zdzqlufu.p.m4p",
    "artistId" : 909253,
    "trackName" : "Banana Pancakes",
    "collectionName" : "In Between Dreams",
    "artistViewUrl" : "http:// itunes.apple.com/WebObjects/ MZStore.woa/wa/viewAlbum?i=68615807&id=68615813&s=143462",
    "discNumber" : 1,
    "trackCount" : 14,
    "wrapperType" : "track",
    "currency" : "USD",
    "collectionId" : 120954021,
    "isStreamable" : true,
    "trackExplicitness" : "track",
    "collectionViewURL" : "http:// itunes.apple.com/WebObjects/ MZStore.woa/wa/viewAlbum?i=68615807&id=68615813&s=143462",
    "trackNumber" : 1,
    "trackId" : 120954025,
    "kind" : "book",
    "collectionPrice" : 10.99,
    "discCount" : 1,
    "primaryGenreName" : "Rock",
    "trackPrice" : 0.99,
    "collectionExplicitness" : "track",
    "artworkUrl60" : "http:// a1.itunes.apple.com/jp/r10/Music/ y2005/m06/d03/h05/s05.oazjtxkw.60×60-75.jpg",
    "trackViewUrl" : "http:// itunes.apple.com/WebObjects/ MZStore.woa/wa/viewAlbum?i=68615807&id=68615813&s=143462",
    "trackCensoredName" : "S**t Happens",
    "artistName" : "Jack Johnson",
    "collectionCensoredName" : "S**t Happens"
  } ]
}}]
     
     - parameter term: (query) The URL-encoded text string you want to search for.  For example: jack+johnson.  URL encoding replaces spaces with the plus (+) character and all characters except the following are encoded: letters, numbers, periods (.), dashes (-), underscores (_), and asterisks (*)  
     - parameter country: (query) The two-letter country code for the store you want to search. The search uses the default store front for the specified country.  See [ISO 3166](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)  
     - parameter media: (query) The media type you want to search for.   (optional, default to all)
     - parameter limit: (query) The number of search results you want the iTunes Store to return.  value allowed for [1, 200]  (optional, default to 50)

     - returns: RequestBuilder<InlineResponse200> 
     */
    open class func searchByTermWithRequestBuilder(term: String, country: String, media: Media_searchByTerm? = nil, limit: Int? = nil) -> RequestBuilder<SearchResponse> {
        let path = "/search"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "term": term, 
            "country": country, 
            "media": media?.rawValue,
            "limit": limit?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<SearchResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
